# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
name: 'Preview Java Snippet Compilation Tests'

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/microsoft-graph-docs
     ref: master
   - repository: msgraph-sdk-java
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/msgraph-sdk-java
     ref: dev
   - repository: msgraph-sdk-java-core
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/msgraph-sdk-java-core
     ref: master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: java-templates/java-prepare.yml
- template: common-templates/checkout.yml
- template: java-templates/build-sdk-core.yml
- template: java-templates/build-sdk.yml
- template: java-templates/java-replace-local-path.yml
  parameters:
    projectFileName: JavaV1Tests
    javaPreviewLibPath: '$(Build.SourcesDirectory)'
- template: compile-run-tests-template.yml
  parameters:
    projectFileName: JavaV1Tests
    runName: 'Preview Java Snippet Compilation Tests $(testRunTitle)'
